### ISSUE TITLE
MenuItemProxy items fail to register internal callables

### ISSUE THREAD

**Issue by Mouthlessbobcat** [theodox/mGui#45] opened 2016-10-17 18:06 UTC
CallbackProxy instances created via the get_weak_reference factory method don't have the correct __name__ attribute of their internal function object.

```
Traceback (most recent call last):
  File "C:\ULDev\source\ulMaya\external\mGui\mGui\menu_loader.py", line 165, in instantiate
    new_item.command += cp
  File "C:\ULDev\source\ulMaya\external\mGui\mGui\events.py", line 87, in _add_handler
    self._Handlers.add(get_weak_reference(handler))
  File "C:\ULDev\source\ulMaya\external\mGui\mGui\events.py", line 237, in get_weak_reference
    return WeakMethodFree(f)
  File "C:\ULDev\source\ulMaya\external\mGui\mGui\events.py", line 213, in __init__
    self._ref_name = f.__name__
AttributeError: 'CallbackProxy' object has no attribute '__name__'
```

**Comment by Mouthlessbobcat** [comment] 2016-10-17 18:08
Proposed fix is to override CallbackProxy's __name__ to its wrapped internal function.

```
    def __name__(self):
        return self.func.__name__
```

Would it be useful/correct to implement the adapter pattern so that all missing attributes on CallbackProxy are redirected to its wrapped func?

**Comment by theodox** [comment] 2016-10-17 18:37
@bob-white  I think this originated in one of yours - what was the original intent? Is there a matching change in menuLoader that makes this not an issue?

**Comment by bob-white** [comment] 2016-10-17 20:59
The original intent was to provide clearer messages during a DeadReferenceError, specifically identifying which function had slipped out of scope.
However I forgot that not all callables have a `__name__` attribute.

It looks like the issue is that menu_loader is wrapping its callbacks in the `CallbackProxy` object, specifically so that the functions remain in scope similar to #40.

I can put a patch together that will just default a name of 'unnamed' if the callable lacks the `__name__` attribute, and add the attribute to the `CallbackProxy` class so that it benefits from the better error messages.

**Comment by theodox** [comment] 2016-10-18 04:24
@Mouthlessbobcat  - does bob's fix sound right to you?

**Comment by Mouthlessbobcat** [comment] 2016-10-18 16:08
@bob-white , @theodox  That change sounds good to me! Thanks for looking into it.

**Comment by theodox** [comment] 2016-10-18 16:38
@Mouthlessbobcat  - merged.  I'll close the issue when we're sure it works!

**Comment by theodox** [comment] 2016-10-19 20:39
@Mouthlessbobcat can I close this guy out?

**Comment by Mouthlessbobcat** [comment] 2016-10-19 20:43
@theodox  Yup! Looks fine to me.

**Closed** 2016-10-19 22:17 UTC
Labels: bug
